#!/usr/bin/env python3
"""Generate src/pyobs-interfaces.ts from pyobs-core interface definitions.

Usage:
    python3 scripts/generate-interfaces.py [--pyobs-core PATH]

PATH defaults to ../../pyobs-core relative to this script (i.e. a sibling
checkout of pyobs-core next to pyobs-web-client).
"""

import argparse
import inspect
import json
import sys
import types
import typing
from pathlib import Path


def parse_args() -> argparse.Namespace:
    default_core = Path(__file__).parent.parent.parent / "pyobs-core"
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--pyobs-core", default=str(default_core), metavar="PATH",
                   help="Path to pyobs-core checkout (default: %(default)s)")
    return p.parse_args()


# ── type mapping ─────────────────────────────────────────────────────────────

def _is_union(ann) -> bool:
    return (
        typing.get_origin(ann) is typing.Union
        or isinstance(ann, types.UnionType)
    )


def _union_args(ann) -> tuple:
    if isinstance(ann, types.UnionType):
        return ann.__args__
    return typing.get_args(ann)


def py_type_to_ts(ann) -> str:
    """Map a Python parameter annotation to a TypeScript primitive type."""
    if ann is inspect.Parameter.empty:
        return "string"

    if _is_union(ann):
        # e.g. str | None  →  unwrap and map the non-None side
        non_none = [a for a in _union_args(ann) if a is not type(None)]
        return py_type_to_ts(non_none[0]) if len(non_none) == 1 else "string"

    if ann is float or ann is int:
        return "number"
    if ann is str:
        return "string"
    if ann is bool:
        return "boolean"
    # StrEnum subclasses (MotionStatus, ExposureStatus, …) → string
    if isinstance(ann, type) and issubclass(ann, str):
        return "string"

    return "string"  # safe fallback for anything exotic


# ── extraction ────────────────────────────────────────────────────────────────

def own_abstract_methods(cls) -> dict:
    """Return {name: fn} for abstract methods defined directly on cls."""
    return {
        name: val
        for name, val in cls.__dict__.items()
        if callable(val)
        and getattr(val, "__isabstractmethod__", False)
        and not name.startswith("_")
    }


def process_interface(cls) -> dict:
    doc = (inspect.getdoc(cls) or "").split("\n")[0].strip()
    methods: dict = {}

    for method_name, method in sorted(own_abstract_methods(cls).items()):
        try:
            hints = typing.get_type_hints(method)
        except Exception:
            hints = {}

        sig = inspect.signature(method)
        params = []

        for param_name, param in sig.parameters.items():
            if param_name == "self":
                continue
            if param.kind in (inspect.Parameter.VAR_KEYWORD,
                               inspect.Parameter.VAR_POSITIONAL):
                continue  # skip *args / **kwargs

            ann = hints.get(param_name, inspect.Parameter.empty)
            optional = (
                param.default is not inspect.Parameter.empty
                or (_is_union(ann) and type(None) in _union_args(ann))
            )

            params.append({
                "name": param_name,
                "type": py_type_to_ts(ann),
                "optional": optional,
            })

        method_doc = (inspect.getdoc(method) or "").split("\n")[0].strip()
        methods[method_name] = {"doc": method_doc, "params": params}

    return {"doc": doc, "methods": methods}


# ── main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    args = parse_args()
    core_path = Path(args.pyobs_core)

    if not (core_path / "pyobs" / "interfaces").exists():
        sys.exit(f"ERROR: pyobs-core not found at {core_path}")

    sys.path.insert(0, str(core_path))

    import pyobs.interfaces as ifaces  # noqa: E402  (intentional late import)
    from pyobs.interfaces.interface import Interface  # noqa: E402

    interfaces: dict = {}
    for name in ifaces.__all__:
        if name == "Interface":
            continue
        cls = getattr(ifaces, name)
        if isinstance(cls, type) and issubclass(cls, Interface):
            interfaces[name] = process_interface(cls)

    out_path = Path(__file__).parent.parent / "src" / "pyobs-interfaces.ts"
    ts = "\n".join([
        "// AUTO-GENERATED by scripts/generate-interfaces.py — do not edit by hand",
        "",
        "export type ParamType = 'number' | 'string' | 'boolean'",
        "",
        "export type ParamDef = {",
        "  name: string",
        "  type: ParamType",
        "  optional: boolean",
        "}",
        "",
        "export type MethodDef = {",
        "  doc: string",
        "  params: ParamDef[]",
        "}",
        "",
        "export type InterfaceDef = {",
        "  doc: string",
        "  methods: Record<string, MethodDef>",
        "}",
        "",
        "export const PYOBS_INTERFACES: Record<string, InterfaceDef> = "
        + json.dumps(interfaces, indent=2),
        "",
    ])

    out_path.write_text(ts)
    print(f"Wrote {len(interfaces)} interfaces → {out_path}")


if __name__ == "__main__":
    main()
