// AUTO-GENERATED by scripts/generate-interfaces.py — do not edit by hand

export type ParamType = 'number' | 'string' | 'boolean'

export type ParamDef = {
  name: string
  type: ParamType
  optional: boolean
}

export type MethodDef = {
  doc: string
  params: ParamDef[]
}

export type InterfaceDef = {
  doc: string
  methods: Record<string, MethodDef>
}

export const PYOBS_INTERFACES: Record<string, InterfaceDef> = {
  "IAbortable": {
    "doc": "The module has an abortable action.",
    "methods": {
      "abort": {
        "doc": "Abort current actions.",
        "params": []
      }
    }
  },
  "IAcquisition": {
    "doc": "The module can acquire a target, usually by accessing a telescope and a camera.",
    "methods": {
      "acquire_target": {
        "doc": "Acquire target at given coordinates.",
        "params": []
      }
    }
  },
  "ILatLon": {
    "doc": "The module can move to general Lat/Lon coordinates, which have to be async defined by the module itself.",
    "methods": {
      "get_latlon": {
        "doc": "Returns current Latitude and Longitude.",
        "params": []
      },
      "move_latlon": {
        "doc": "Moves to given coordinates.",
        "params": [
          {
            "name": "lat",
            "type": "number",
            "optional": false
          },
          {
            "name": "lon",
            "type": "number",
            "optional": false
          }
        ]
      }
    }
  },
  "IAutoFocus": {
    "doc": "The module can perform an auto-focus.",
    "methods": {
      "auto_focus": {
        "doc": "Perform an auto-focus series.",
        "params": [
          {
            "name": "count",
            "type": "number",
            "optional": false
          },
          {
            "name": "step",
            "type": "number",
            "optional": false
          },
          {
            "name": "exposure_time",
            "type": "number",
            "optional": false
          }
        ]
      },
      "auto_focus_status": {
        "doc": "Returns current status of auto focus.",
        "params": []
      }
    }
  },
  "IAutoGuiding": {
    "doc": "The module can perform auto-guiding.",
    "methods": {}
  },
  "IAutonomous": {
    "doc": "The module does some autonomous actions, mainly used for warnings to users.",
    "methods": {}
  },
  "IBinning": {
    "doc": "The camera supports binning, to be used together with :class:`~pyobs.interfaces.ICamera`.",
    "methods": {
      "get_binning": {
        "doc": "Returns the camera binning.",
        "params": []
      },
      "list_binnings": {
        "doc": "List available binnings.",
        "params": []
      },
      "set_binning": {
        "doc": "Set the camera binning.",
        "params": [
          {
            "name": "x",
            "type": "number",
            "optional": false
          },
          {
            "name": "y",
            "type": "number",
            "optional": false
          }
        ]
      }
    }
  },
  "ICalibrate": {
    "doc": "The module can calibrate a device.",
    "methods": {
      "calibrate": {
        "doc": "Calibrate the device.",
        "params": []
      }
    }
  },
  "ICamera": {
    "doc": "The module controls a camera.",
    "methods": {}
  },
  "IConfig": {
    "doc": "The module allows access to some of its configuration options.",
    "methods": {
      "get_config_caps": {
        "doc": "Returns dict of all config capabilities. First value is whether it has a getter, second is for the setter,",
        "params": []
      },
      "get_config_value": {
        "doc": "Returns current value of config item with given name.",
        "params": [
          {
            "name": "name",
            "type": "string",
            "optional": false
          }
        ]
      },
      "get_config_value_options": {
        "doc": "Returns possible values for config item with given name.",
        "params": [
          {
            "name": "name",
            "type": "string",
            "optional": false
          }
        ]
      },
      "set_config_value": {
        "doc": "Sets value of config item with given name.",
        "params": [
          {
            "name": "name",
            "type": "string",
            "optional": false
          },
          {
            "name": "value",
            "type": "string",
            "optional": false
          }
        ]
      }
    }
  },
  "ICooling": {
    "doc": "The module can control the cooling of a device.",
    "methods": {
      "get_cooling": {
        "doc": "Returns the current status for the cooling.",
        "params": []
      },
      "set_cooling": {
        "doc": "Enables/disables cooling and sets setpoint.",
        "params": [
          {
            "name": "enabled",
            "type": "boolean",
            "optional": false
          },
          {
            "name": "setpoint",
            "type": "number",
            "optional": false
          }
        ]
      }
    }
  },
  "IDome": {
    "doc": "The module controls a dome, i.e. a :class:`~pyobs.interfaces.IRoof` with a rotating roof.",
    "methods": {}
  },
  "IExposure": {
    "doc": "The module controls a camera.",
    "methods": {
      "get_exposure_progress": {
        "doc": "Returns the progress of the current exposure in percent.",
        "params": []
      },
      "get_exposure_status": {
        "doc": "Returns the current status of the camera, which is one of 'idle', 'exposing', or 'readout'.",
        "params": []
      }
    }
  },
  "IExposureTime": {
    "doc": "The camera supports exposure times, to be used together with :class:`~pyobs.interfaces.ICamera`.",
    "methods": {
      "get_exposure_time": {
        "doc": "Returns the exposure time in seconds.",
        "params": []
      },
      "get_exposure_time_left": {
        "doc": "Returns the remaining exposure time on the current exposure in seconds.",
        "params": []
      },
      "set_exposure_time": {
        "doc": "Set the exposure time in seconds.",
        "params": [
          {
            "name": "exposure_time",
            "type": "number",
            "optional": false
          }
        ]
      }
    }
  },
  "IFilters": {
    "doc": "The module can change filters in a device.",
    "methods": {
      "get_filter": {
        "doc": "Get currently set filter.",
        "params": []
      },
      "list_filters": {
        "doc": "List available filters.",
        "params": []
      },
      "set_filter": {
        "doc": "Set the current filter.",
        "params": [
          {
            "name": "filter_name",
            "type": "string",
            "optional": false
          }
        ]
      }
    }
  },
  "IFitsHeaderAfter": {
    "doc": "The module provides some additional header entries for FITS headers after some event (usually the end of the",
    "methods": {
      "get_fits_header_after": {
        "doc": "Returns FITS header for the current status of this module.",
        "params": [
          {
            "name": "namespaces",
            "type": "string",
            "optional": true
          }
        ]
      }
    }
  },
  "IFitsHeaderBefore": {
    "doc": "The module provides some additional header entries for FITS headers before some event (usually the start of the",
    "methods": {
      "get_fits_header_before": {
        "doc": "Returns FITS header for the current status of this module.",
        "params": [
          {
            "name": "namespaces",
            "type": "string",
            "optional": true
          }
        ]
      }
    }
  },
  "IFlatField": {
    "doc": "The module performs flat-fielding.",
    "methods": {
      "flat_field": {
        "doc": "Do a series of flat fields.",
        "params": [
          {
            "name": "count",
            "type": "number",
            "optional": true
          }
        ]
      }
    }
  },
  "IFocusModel": {
    "doc": "The module provides a model for the telescope focus, e.g. based on temperatures.",
    "methods": {
      "get_optimal_focus": {
        "doc": "Returns the optimal focus.",
        "params": []
      },
      "set_optimal_focus": {
        "doc": "Sets optimal focus.",
        "params": []
      }
    }
  },
  "IFocuser": {
    "doc": "The module is a focusing device.",
    "methods": {
      "get_focus": {
        "doc": "Return current focus.",
        "params": []
      },
      "get_focus_offset": {
        "doc": "Return current focus offset.",
        "params": []
      },
      "set_focus": {
        "doc": "Sets new focus.",
        "params": [
          {
            "name": "focus",
            "type": "number",
            "optional": false
          }
        ]
      },
      "set_focus_offset": {
        "doc": "Sets focus offset.",
        "params": [
          {
            "name": "offset",
            "type": "number",
            "optional": false
          }
        ]
      }
    }
  },
  "IGain": {
    "doc": "The camera supports setting of gain, to be used together with :class:`~pyobs.interfaces.ICamera`.",
    "methods": {
      "get_gain": {
        "doc": "Returns the camera gain.",
        "params": []
      },
      "get_offset": {
        "doc": "Returns the camera offset.",
        "params": []
      },
      "set_gain": {
        "doc": "Set the camera gain.",
        "params": [
          {
            "name": "gain",
            "type": "number",
            "optional": false
          }
        ]
      },
      "set_offset": {
        "doc": "Set the camera offset.",
        "params": [
          {
            "name": "offset",
            "type": "number",
            "optional": false
          }
        ]
      }
    }
  },
  "IImageFormat": {
    "doc": "The module supports different image formats (e.g. INT16, FLOAT32), mainly used by cameras.",
    "methods": {
      "get_image_format": {
        "doc": "Returns the camera image format.",
        "params": []
      },
      "list_image_formats": {
        "doc": "List available image formats.",
        "params": []
      },
      "set_image_format": {
        "doc": "Set the camera image format.",
        "params": [
          {
            "name": "fmt",
            "type": "string",
            "optional": false
          }
        ]
      }
    }
  },
  "IData": {
    "doc": "The module can grab and return an image from whatever device.",
    "methods": {
      "grab_data": {
        "doc": "Grabs an image and returns reference.",
        "params": [
          {
            "name": "broadcast",
            "type": "boolean",
            "optional": true
          }
        ]
      }
    }
  },
  "IImageType": {
    "doc": "The module supports different image types (e.g. object, bias, dark, etc), mainly used by cameras.",
    "methods": {
      "get_image_type": {
        "doc": "Returns the current image type.",
        "params": []
      },
      "set_image_type": {
        "doc": "Set the image type.",
        "params": [
          {
            "name": "image_type",
            "type": "string",
            "optional": false
          }
        ]
      }
    }
  },
  "IMode": {
    "doc": "The module can change modes in a device.",
    "methods": {
      "get_mode": {
        "doc": "Get currently set mode.",
        "params": [
          {
            "name": "group",
            "type": "number",
            "optional": true
          }
        ]
      },
      "list_modes": {
        "doc": "List available modes.",
        "params": [
          {
            "name": "group",
            "type": "number",
            "optional": true
          }
        ]
      },
      "set_mode": {
        "doc": "Set the current mode.",
        "params": [
          {
            "name": "mode",
            "type": "string",
            "optional": false
          },
          {
            "name": "group",
            "type": "number",
            "optional": true
          }
        ]
      }
    }
  },
  "IModule": {
    "doc": "The module is actually a module. Implemented by all modules.",
    "methods": {
      "get_error_string": {
        "doc": "Returns description of error, if any.",
        "params": []
      },
      "get_label": {
        "doc": "Returns label of module.",
        "params": []
      },
      "get_state": {
        "doc": "Returns current state of module.",
        "params": []
      },
      "get_version": {
        "doc": "Returns pyobs version of module.",
        "params": []
      },
      "reset_error": {
        "doc": "Reset error of module, if any.",
        "params": []
      }
    }
  },
  "IMotion": {
    "doc": "The module controls a device that can move.",
    "methods": {
      "get_motion_status": {
        "doc": "Returns current motion status.",
        "params": [
          {
            "name": "device",
            "type": "string",
            "optional": true
          }
        ]
      },
      "init": {
        "doc": "Initialize device.",
        "params": []
      },
      "park": {
        "doc": "Park device.",
        "params": []
      },
      "stop_motion": {
        "doc": "Stop the motion.",
        "params": [
          {
            "name": "device",
            "type": "string",
            "optional": true
          }
        ]
      }
    }
  },
  "IMultiFiber": {
    "doc": "An interface for multi-fiber setups that helps to set/get a fiber and retrieve position and size of the",
    "methods": {
      "abort": {
        "doc": "Abort current actions.",
        "params": []
      },
      "get_fiber": {
        "doc": "Returns the name of the currently active fiber.",
        "params": []
      },
      "get_fiber_count": {
        "doc": "Returns the number of available fibers in the setup.",
        "params": []
      },
      "get_pixel_position": {
        "doc": "Get pixel position of currently active fiber on acquisition/guiding image.",
        "params": []
      },
      "get_radius": {
        "doc": "Get radius of currently active fiber on acquisition/guiding image.",
        "params": []
      },
      "list_fiber_names": {
        "doc": "Returns the names of all available fibers.",
        "params": []
      },
      "set_fiber": {
        "doc": "Sets the currently active filter. Must be in list returned by @list_fiber_names.",
        "params": [
          {
            "name": "fiber",
            "type": "string",
            "optional": false
          }
        ]
      }
    }
  },
  "IPointingAltAz": {
    "doc": "The module can move to Alt/Az coordinates, usually combined with :class:`~pyobs.interfaces.ITelescope`.",
    "methods": {
      "get_altaz": {
        "doc": "Returns current Alt and Az.",
        "params": []
      },
      "move_altaz": {
        "doc": "Moves to given coordinates.",
        "params": [
          {
            "name": "alt",
            "type": "number",
            "optional": false
          },
          {
            "name": "az",
            "type": "number",
            "optional": false
          }
        ]
      }
    }
  },
  "IPointingHelioprojective": {
    "doc": "The module can move to Mu/Psi coordinates, usually combined with :class:`~pyobs.interfaces.ITelescope`.",
    "methods": {
      "get_helioprojective": {
        "doc": "Returns current theta x/y",
        "params": []
      },
      "move_helioprojective": {
        "doc": "Moves on given coordinates.",
        "params": [
          {
            "name": "theta_x",
            "type": "number",
            "optional": false
          },
          {
            "name": "theta_y",
            "type": "number",
            "optional": false
          }
        ]
      }
    }
  },
  "IPointingHGS": {
    "doc": "The module can move to Mu/Psi coordinates, usually combined with :class:`~pyobs.interfaces.ITelescope`.",
    "methods": {
      "get_hgs_lon_lat": {
        "doc": "Returns current longitude and latitude position.",
        "params": []
      },
      "move_hgs_lon_lat": {
        "doc": "Moves on given coordinates.",
        "params": [
          {
            "name": "lon",
            "type": "number",
            "optional": false
          },
          {
            "name": "lat",
            "type": "number",
            "optional": false
          }
        ]
      }
    }
  },
  "IPointingRaDec": {
    "doc": "The module can move to RA/Dec coordinates, usually combined with :class:`~pyobs.interfaces.ITelescope`.",
    "methods": {
      "get_radec": {
        "doc": "Returns current RA and Dec.",
        "params": []
      },
      "move_radec": {
        "doc": "Starts tracking on given coordinates.",
        "params": [
          {
            "name": "ra",
            "type": "number",
            "optional": false
          },
          {
            "name": "dec",
            "type": "number",
            "optional": false
          }
        ]
      }
    }
  },
  "IPointingSeries": {
    "doc": "The module provides the interface for a device that initializes and finalizes a pointing series and adds points",
    "methods": {
      "add_pointing_measurement": {
        "doc": "Add a new measurement to the pointing series.",
        "params": []
      }
    }
  },
  "IReady": {
    "doc": "The module can be in a \"not ready\" state for science and need to be initialized in some way.",
    "methods": {
      "is_ready": {
        "doc": "Returns the device is \"ready\", whatever that means for the specific device.",
        "params": []
      }
    }
  },
  "IRoof": {
    "doc": "The module controls a roof.",
    "methods": {}
  },
  "IRotation": {
    "doc": "The module controls a device that can rotate.",
    "methods": {
      "get_rotation": {
        "doc": "Returns the current rotation angle.",
        "params": []
      },
      "set_rotation": {
        "doc": "Sets the rotation angle to the given value in degrees.",
        "params": [
          {
            "name": "angle",
            "type": "number",
            "optional": false
          }
        ]
      }
    }
  },
  "IRunnable": {
    "doc": "The module has some action that can be started remotely.",
    "methods": {
      "run": {
        "doc": "Perform module task",
        "params": []
      }
    }
  },
  "IRunning": {
    "doc": "The module can be running.",
    "methods": {
      "is_running": {
        "doc": "Whether a service is running.",
        "params": []
      }
    }
  },
  "IScriptRunner": {
    "doc": "The module can execute a script.",
    "methods": {
      "run_script": {
        "doc": "Run the given script.",
        "params": [
          {
            "name": "script",
            "type": "string",
            "optional": false
          }
        ]
      }
    }
  },
  "IStartStop": {
    "doc": "The module can be started and stopped.",
    "methods": {
      "start": {
        "doc": "Starts a service.",
        "params": []
      },
      "stop": {
        "doc": "Stops a service.",
        "params": []
      }
    }
  },
  "ISyncTarget": {
    "doc": "The module can synchronize a target, e.g. via a telescope control software behinde an",
    "methods": {
      "sync_target": {
        "doc": "Synchronize device on current target.",
        "params": []
      }
    }
  },
  "ITelescope": {
    "doc": "The module controls a telescope.",
    "methods": {}
  },
  "ITemperatures": {
    "doc": "The module can return temperatures measured on some device.",
    "methods": {
      "get_temperatures": {
        "doc": "Returns all temperatures measured by this module.",
        "params": []
      }
    }
  },
  "IOffsetsAltAz": {
    "doc": "The module supports Alt/Az offsets, usually combined with :class:`~pyobs.interfaces.ITelescope` and",
    "methods": {
      "get_offsets_altaz": {
        "doc": "Get Alt/Az offset.",
        "params": []
      },
      "set_offsets_altaz": {
        "doc": "Move an Alt/Az offset.",
        "params": [
          {
            "name": "dalt",
            "type": "number",
            "optional": false
          },
          {
            "name": "daz",
            "type": "number",
            "optional": false
          }
        ]
      }
    }
  },
  "IOffsetsRaDec": {
    "doc": "The module supports RA/Dec offsets, usually combined with :class:`~pyobs.interfaces.ITelescope` and",
    "methods": {
      "get_offsets_radec": {
        "doc": "Get RA/Dec offset.",
        "params": []
      },
      "set_offsets_radec": {
        "doc": "Move an RA/Dec offset.",
        "params": [
          {
            "name": "dra",
            "type": "number",
            "optional": false
          },
          {
            "name": "ddec",
            "type": "number",
            "optional": false
          }
        ]
      }
    }
  },
  "ISpectrograph": {
    "doc": "The module controls a camera.",
    "methods": {}
  },
  "IVideo": {
    "doc": "The module controls a video streaming device.",
    "methods": {
      "get_video": {
        "doc": "Returns path to video.",
        "params": []
      }
    }
  },
  "IWeather": {
    "doc": "The module acts as a weather station.",
    "methods": {
      "get_current_weather": {
        "doc": "Returns current weather.",
        "params": []
      },
      "get_sensor_value": {
        "doc": "Return value for given sensor.",
        "params": [
          {
            "name": "station",
            "type": "string",
            "optional": false
          },
          {
            "name": "sensor",
            "type": "string",
            "optional": false
          }
        ]
      },
      "get_weather_status": {
        "doc": "Returns status of object in form of a dictionary. See other interfaces for details.",
        "params": []
      },
      "is_weather_good": {
        "doc": "Whether the weather is good to observe.",
        "params": []
      }
    }
  },
  "IWindow": {
    "doc": "The camera supports windows, to be used together with :class:`~pyobs.interfaces.ICamera`.",
    "methods": {
      "get_full_frame": {
        "doc": "Returns full size of CCD.",
        "params": []
      },
      "get_window": {
        "doc": "Returns the camera window.",
        "params": []
      },
      "set_window": {
        "doc": "Set the camera window.",
        "params": [
          {
            "name": "left",
            "type": "number",
            "optional": false
          },
          {
            "name": "top",
            "type": "number",
            "optional": false
          },
          {
            "name": "width",
            "type": "number",
            "optional": false
          },
          {
            "name": "height",
            "type": "number",
            "optional": false
          }
        ]
      }
    }
  }
}
